// Scripted Pipeline
// node {
// 	stage('Build') {
// 		echo "Build"
// 	}
// 	stage('Test') {
// 		echo "Test"
// 	}
// 	stage('Integration Test') {
// 		echo "Integration Test"
// 	}
// 	stage('Deploying') {
// 		echo "Deploying"
// 	}
// }
// node{
// 	echo "Build"
// 	echo "Test"
// }

// Declarative Pipeline
// Pipeline{
// 	agent any

// 	options{
// 		retry(3)
// 		timeout(time:1, unit:'MINUTES')
// 		timestamps()
// 	}

// 	stages{
// 		stage('Build'){
// 			steps{
// 				echo "Build"
// 			}
// 		}
// 		stage('Test'){
// 			steps{
// 				echo "Test"
// 			}
// 		}
// 		stage('Integration Test'){
// 			steps{
// 				echo "Integration Test"
// 			}
// 		}
// 		stage('Deploying'){
// 			steps{
// 				echo "Deploying"
// 			}
// 		}
// 	}
// 	post{
// 		always{
// 			echo "This will always execute"
// 		}
// 		success{
// 			echo "This will execute on success"
// 		}
// 		failure{
// 			echo "This will execute on failure"
// 		}
// 		changed{
// 			echo "This will execute on changed status"
// 		}
// 		unstable{
// 			echo "This will execute on unstable"
// 		}
// 	}
// }


// Docker agent
// pipeline{
// 	agent{
// 		docker{
// 			image 'maven:3.8.1-jdk-11'
// 			args '-v /root/.m2:/root/.m2'
// 		}
// 	}

// 	stages{
// 		stage('build'){
// 			steps{
// 				sh 'mvn --version'
// 			}
// 		}
// 	}
// }


// Variables and environment
// pipeline{
// 	agent any

// 	stages{
// 		stage('Build'){
// 			steps{
// 				echo "Building the application in ${env.BRANCH_NAME} branch"
// 				echo 'buildNumber: ${env.BUILD_NUMBER}'
// 				echo 'env.Build_ID'
// 				echo "env.WORKSPACE: ${env.WORKSPACE}"
// 				echo "env.JOB_NAME: ${env.JOB_NAME}"
// 				echo "env.BUILD_URL: ${env.BUILD_URL}"
// 				echo "env.BUILD_TAG: ${env.BUILD_TAG}"
// 			}
// 		}
// 	}
// }

// Docker and maven
// pipeline{
//     environment{
//         dockerHome = tool 'myDocker'
//         mavenHome = tool 'myMaven'
//         PATH = "${env.dockerHome}/bin:${env.mavenHome}/bin:${env.PATH}"
//     }
//     agent any

//     stages{
//         stage('build'){
//             steps{
//                 sh 'docker --version'
//                 sh 'mvn --version'
//             }
//         }
//     }
// }

// run unit tests and integration tests in parallel
// pipeline{
//     environment{
//         dockerHome = tool 'myDocker'
//         mavenHome = tool 'myMaven'
//         PATH = "${env.dockerHome}/bin:${env.mavenHome}/bin:${env.PATH}"
//     }
//     agent any

//     stages{
//         stage('checking version'){
//             steps{
//                 sh 'docker --version'
//                 sh 'mvn --version'
//             }
//         }
//         stage('compile'){
//             steps{
//                 dir('currency-exchange-microservice') {
//                     sh 'mvn clean compile'
//                 }
//             }
//         }
//         stage('test'){
//             parallel{
//                 stage('unit test'){
//                     steps{
//                         echo "Starting Unit Tests..."
//                         // Change into the folder where pom.xml exists
//                             dir('currency-exchange-microservice') {
//                             sh 'mvn clean compile'
//                         }
//                     }
//                 }
//                 stage('integration test'){
//                     steps{
//                         // sh 'mvn verify -DskipUnitTests=true'
//                         echo "Integration tests executed"
//                     }
//                 }
//             }
//         }
//     }
// }


// build docker image
pipeline{
    environment{
        dockerHome = tool 'myDocker'
        mavenHome = tool 'myMaven'
        PATH = "${env.dockerHome}/bin:${env.mavenHome}/bin:${env.PATH}"
    }
    agent any

    stages{
        stage('compile'){
            steps{
                dir('currency-exchange-microservice') {
                    sh 'mvn clean compile'
                }
            }
        }
        stage('build docker image'){
            steps{
                // "docker build -t in28min/currency-exchange-devops:${env.BUILD_TAG}"
                script{
                    dockerImnage = docker.build("tejas002/currency-exchange-devops:${env.BUILD_TAG}")
                }
            }
        }
        stage('package jar'){
            steps{
                sh 'mvn clean -DskipTests'
            }
        }
        stage('push docker image'){
            steps{
                script{
                    docker.withRegistry('', 'dockerhub')  {
                        dockerImage.push()
                        dockerImage.push('latest')
                    }
                }
            }
        }
    }
}

